### ISSUE TITLE
Implement search of themes

### ISSUE THREAD

**Issue by nmenag** [mattvh/jekyllthemes#204] opened 2015-10-23 05:48 UTC

**Comment by nandomoreirame** [comment] 2015-12-18 00:03
:+1:

**Comment by nandomoreirame** [comment] 2016-01-04 15:52
@mattvh I can do it if they want.

**Comment by nmenag** [comment] 2016-01-11 04:24
@nandomoreirame  That would be great!

**Comment by gynter** [comment] 2016-01-11 06:28
This is a duplicate of #104.

**Closed by gynter** 2016-01-11 06:28 UTC
